name: CI - Unit Tests

on: [push]

jobs:
    run-unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest

        # Definir os passos necessarios para fazer o download do app e aplicar os testes

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: 18
                cache: "npm"
            - run: npm ci
            - run: npm run test:unit
              env:
                PORT: 3000
                NODE_ENV: test
                JWT_SECRET: FAKE
                JWT_EXPIRES_IN: 86400
                DATABASE_URL: fake_url

